#! /usr/bin/python
import shutil
import sys
import os
import tempfile
import time
import logging
base = "/var/spool/voipmonitor"
logger = logging.getLogger('voicexfer')
hdlr = logging.FileHandler('/var/log/voicexfer.log')
formatter = logging.Formatter('%(asctime)s %(levelname)s %(message)s')
hdlr.setFormatter(formatter)
logger.addHandler(hdlr)
logger.setLevel(logging.DEBUG)

end = sys.argv[2]
id = sys.argv[1]
dest = "/home/mmilmeisters/recordings"

logger.info("[~start~] " + sys.argv[2] + "/" + "AUDIO" + "/" +   sys.argv[1] )
def gtfo():
#	print "Get The Fuck Out"
#	logger.info()
	sys.exit(0)

def nomount():
logger.error("[-] " + "Attempted to remount but failed - Manual required" + "\r\n" + "mv " + base + "/"  + sys.argv[2] + "/" + "AUDIO" + "/" +   sys.argv[1] + ".wav "   + dest  )
	sys.exit(0)


import subprocess

def volumeCheck(volume_name):
    """This function will check volume name is mounted or not.
    """
volume_name = "rec"
volumeCheck(volume_name)

p = subprocess.Popen(['df', '-h'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
p1, err = p.communicate()
pattern = p1

if pattern.find(volume_name) != -1:
	logger.info(" Mount available " + id)
#	print "found"
else:
	logger.error(" Mount missing " + id )

	from subprocess import call
	call(["mount", "/home/mmilmeisters/recordings"])
#	print " not found"
	logger.info(" Attempting to mount if fail will exit => " + id)
	time.sleep(5)


import subprocess
def volumeCheck2(volume_name2):
    """This function will check volume name is mounted or not.
    """
volume_name2 = "rec"
volumeCheck2(volume_name2)

p = subprocess.Popen(['df', '-h'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
p1, err = p.communicate()
pattern = p1




if pattern.find(volume_name2) != -1:
        logger.info(" Mount available " + id)
#       print "found"
else:
        logger.error(" Mount missing " + id )
#       print " not found"
        nomount()


if os.path.exists(dest + "/" + id + ".wav"):
#	print "File is Saved"
	logger.info("[+] File id: " + id + " Saved")

	gtfo()
#elif: os.path.exists(dest + "/" + id + ".wav"):
else:
	if os.path.exists(base + '/' +  end + "/" + "AUDIO" + "/" + id + '.wav'):
#		print "[+] File is  Found, moving " + id
		logger.info("[+] File is  Found, moving " + id)
		shutil.move(base + '/' +  end + "/" + "AUDIO" + "/" + id + '.wav', dest + "/" + id + ".wav")
	else:
#		print '[-] File not Found, retry ' + id
		logger.warning("[-] File not Found, retry " + id)
time.sleep(20)

if os.path.exists(dest + "/" + id + ".wav"):
#        print "[+] Second Verify File is saved"
	logger.info("[+] Second Verify File is saved")
	gtfo()
else:

	if os.path.exists(base + '/' +  end + "/" + "AUDIO" + "/" + id + '.wav'):
#        	print "[+] File Found, After Sleep, Moving...."
 		logger.warning("[+] File id " + id + " Found After Sleep Moving")
	       	shutil.move(base + '/' +  end + "/" + "AUDIO" + "/" + id + '.wav', dest + "/" + id + ".wav")
	else:
#        	print '[-] File not Found, After Sleep.. well fuck.... ' + id
		logger.error("[-] File not Found, After Sleep! possibly blank call or unanswered "  + id)
